// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFMm27yVQGLrcOy2_bYpyOUeUZqmzw4Qc',
    appId: '1:121571739816:web:354620d8cfc7d13ca65a9d',
    messagingSenderId: '121571739816',
    projectId: 'repair-miniproject-248e2',
    authDomain: 'repair-miniproject-248e2.firebaseapp.com',
    storageBucket: 'repair-miniproject-248e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO_dM_N0LTT5D1sNfVJysy1TZuAUDgid4',
    appId: '1:121571739816:android:e6f2e4477b309f8aa65a9d',
    messagingSenderId: '121571739816',
    projectId: 'repair-miniproject-248e2',
    storageBucket: 'repair-miniproject-248e2.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFMm27yVQGLrcOy2_bYpyOUeUZqmzw4Qc',
    appId: '1:121571739816:web:739c4bbada7ff2caa65a9d',
    messagingSenderId: '121571739816',
    projectId: 'repair-miniproject-248e2',
    authDomain: 'repair-miniproject-248e2.firebaseapp.com',
    storageBucket: 'repair-miniproject-248e2.appspot.com',
  );
}
